---
- name: stop apache
  hosts: sai-slave     #group name
  gather_facts: true
  remote_user: root
  become: true
  tesks:
    - name: stop apache
      service:
        name: httpd
        state: stopped
        